import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import '../core/theme.dart';
import '../models/study_group.dart';

class GroupStudyScreen extends StatefulWidget {
  final VoidCallback? openDrawer;

  const GroupStudyScreen({super.key, this.openDrawer});

  @override
  State<GroupStudyScreen> createState() => _GroupStudyScreenState();
}

class _GroupStudyScreenState extends State<GroupStudyScreen> {
  final TextEditingController _messageController = TextEditingController();
  final ScrollController _scrollController = ScrollController();
  
  // Mock data
  StudyGroup? _selectedGroup;
  
  final List<StudyGroup> _groups = [
    StudyGroup(
      id: '1',
      courseId: 'math101',
      courseName: 'Mathematics 101',
      members: [
        GroupMember(id: '1', name: 'You', isOnline: true),
        GroupMember(id: '2', name: 'Alex', isOnline: true),
        GroupMember(id: '3', name: 'Sam', isOnline: false),
        GroupMember(id: '4', name: 'Jordan', isOnline: true),
      ],
      messages: [
        GroupMessage(
          id: '1',
          senderId: '2',
          senderName: 'Alex',
          content: 'Hey! Anyone want to study together for the quiz?',
          timestamp: DateTime.now().subtract(const Duration(hours: 2)),
        ),
        GroupMessage(
          id: '2',
          senderId: '4',
          senderName: 'Jordan',
          content: 'I\'m in! When are you free?',
          timestamp: DateTime.now().subtract(const Duration(hours: 1)),
        ),
      ],
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
    ),
    StudyGroup(
      id: '2',
      courseId: 'hist201',
      courseName: 'World History',
      members: [
        GroupMember(id: '1', name: 'You', isOnline: true),
        GroupMember(id: '5', name: 'Taylor', isOnline: true),
        GroupMember(id: '6', name: 'Morgan', isOnline: true),
      ],
      messages: [],
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
    ),
  ];
  
  @override
  void initState() {
    super.initState();
    _selectedGroup = _groups.first;
  }
  
  @override
  void dispose() {
    _messageController.dispose();
    _scrollController.dispose();
    super.dispose();
  }
  
  void _sendMessage() {
    if (_messageController.text.trim().isEmpty || _selectedGroup == null) return;
    
    setState(() {
      _selectedGroup!.messages.add(GroupMessage(
        id: DateTime.now().millisecondsSinceEpoch.toString(),
        senderId: '1',
        senderName: 'You',
        content: _messageController.text,
        timestamp: DateTime.now(),
      ));
    });
    
    _messageController.clear();
    _scrollController.animateTo(
      _scrollController.position.maxScrollExtent,
      duration: const Duration(milliseconds: 300),
      curve: Curves.easeOut,
    );
  }
  
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        leading: widget.openDrawer != null
            ? IconButton(
                icon: const Icon(Icons.menu),
                onPressed: widget.openDrawer,
                tooltip: 'Open menu',
              )
            : null,
        title: const Text('Group Study'),
      ),
      body: Row(
        children: [
          // Groups List
          Container(
            width: 280,
            color: AppTheme.white,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Padding(
                  padding: const EdgeInsets.all(16),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const Text(
                        'Study Groups',
                        style: TextStyle(
                          fontSize: 20,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      const SizedBox(height: 8),
                      Text(
                        'Auto-generated by course',
                        style: TextStyle(
                          fontSize: 12,
                          color: AppTheme.mediumGray,
                        ),
                      ),
                    ],
                  ),
                ),
                Expanded(
                  child: ListView.builder(
                    itemCount: _groups.length,
                    itemBuilder: (context, index) {
                      final group = _groups[index];
                      final isSelected = _selectedGroup?.id == group.id;
                      final unreadCount = group.messages
                          .where((m) => !m.isRead && m.senderId != '1')
                          .length;
                      
                      return InkWell(
                        onTap: () {
                          setState(() {
                            _selectedGroup = group;
                          });
                        },
                        child: Container(
                          color: isSelected
                              ? AppTheme.primaryBlue.withOpacity(0.1)
                              : null,
                          padding: const EdgeInsets.all(16),
                          child: Row(
                            children: [
                              Container(
                                width: 48,
                                height: 48,
                                decoration: BoxDecoration(
                                  gradient: AppTheme.primaryGradient,
                                  borderRadius: BorderRadius.circular(12),
                                ),
                                child: Center(
                                  child: Text(
                                    group.courseName[0].toUpperCase(),
                                    style: const TextStyle(
                                      color: AppTheme.white,
                                      fontSize: 20,
                                      fontWeight: FontWeight.bold,
                                    ),
                                  ),
                                ),
                              ),
                              const SizedBox(width: 12),
                              Expanded(
                                child: Column(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Text(
                                      group.courseName,
                                      style: TextStyle(
                                        fontSize: 14,
                                        fontWeight: isSelected
                                            ? FontWeight.w600
                                            : FontWeight.normal,
                                      ),
                                    ),
                                    const SizedBox(height: 4),
                                    Row(
                                      children: [
                                        ...group.members.take(3).map((member) {
                                          return Container(
                                            width: 6,
                                            height: 6,
                                            margin: const EdgeInsets.only(right: 4),
                                            decoration: BoxDecoration(
                                              color: member.isOnline
                                                  ? AppTheme.successGreen
                                                  : AppTheme.mediumGray,
                                              shape: BoxShape.circle,
                                            ),
                                          );
                                        }),
                                        if (group.members.length > 3)
                                          Text(
                                            '+${group.members.length - 3}',
                                            style: TextStyle(
                                              fontSize: 10,
                                              color: AppTheme.mediumGray,
                                            ),
                                          ),
                                      ],
                                    ),
                                  ],
                                ),
                              ),
                              if (unreadCount > 0)
                                Container(
                                  padding: const EdgeInsets.all(4),
                                  decoration: BoxDecoration(
                                    color: AppTheme.primaryBlue,
                                    shape: BoxShape.circle,
                                  ),
                                  child: Text(
                                    unreadCount.toString(),
                                    style: const TextStyle(
                                      color: AppTheme.white,
                                      fontSize: 10,
                                      fontWeight: FontWeight.bold,
                                    ),
                                  ),
                                ),
                            ],
                          ),
                        ),
                      );
                    },
                  ),
                ),
              ],
            ),
          ),
          
          // Chat Interface
          Expanded(
            child: _selectedGroup == null
                ? const Center(child: Text('Select a group to start chatting'))
                : Column(
                    children: [
                      // Chat Header
                      Container(
                        padding: const EdgeInsets.all(16),
                        color: AppTheme.white,
                        child: Row(
                          children: [
                            Container(
                              width: 40,
                              height: 40,
                              decoration: BoxDecoration(
                                gradient: AppTheme.primaryGradient,
                                borderRadius: BorderRadius.circular(10),
                              ),
                              child: Center(
                                child: Text(
                                  _selectedGroup!.courseName[0].toUpperCase(),
                                  style: const TextStyle(
                                    color: AppTheme.white,
                                    fontSize: 18,
                                    fontWeight: FontWeight.bold,
                                  ),
                                ),
                              ),
                            ),
                            const SizedBox(width: 12),
                            Expanded(
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text(
                                    _selectedGroup!.courseName,
                                    style: const TextStyle(
                                      fontSize: 16,
                                      fontWeight: FontWeight.w600,
                                    ),
                                  ),
                                  Text(
                                    '${_selectedGroup!.members.length} members',
                                    style: TextStyle(
                                      fontSize: 12,
                                      color: AppTheme.mediumGray,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            IconButton(
                              icon: const Icon(Icons.info_outline),
                              onPressed: () {
                                _showGroupInfo();
                              },
                            ),
                          ],
                        ),
                      ),
                      
                      // Messages
                      Expanded(
                        child: Container(
                          color: AppTheme.lightGray,
                          child: ListView.builder(
                            controller: _scrollController,
                            padding: const EdgeInsets.all(16),
                            itemCount: _selectedGroup!.messages.length,
                            itemBuilder: (context, index) {
                              final message = _selectedGroup!.messages[index];
                              final isMe = message.senderId == '1';
                              
                              return Align(
                                alignment: isMe
                                    ? Alignment.centerRight
                                    : Alignment.centerLeft,
                                child: Container(
                                  margin: const EdgeInsets.only(bottom: 12),
                                  constraints: BoxConstraints(
                                    maxWidth:
                                        MediaQuery.of(context).size.width * 0.5,
                                  ),
                                  child: Column(
                                    crossAxisAlignment: isMe
                                        ? CrossAxisAlignment.end
                                        : CrossAxisAlignment.start,
                                    children: [
                                      if (!isMe)
                                        Padding(
                                          padding: const EdgeInsets.only(bottom: 4),
                                          child: Text(
                                            message.senderName,
                                            style: TextStyle(
                                              fontSize: 12,
                                              color: AppTheme.mediumGray,
                                              fontWeight: FontWeight.w600,
                                            ),
                                          ),
                                        ),
                                      Container(
                                        padding: const EdgeInsets.all(12),
                                        decoration: BoxDecoration(
                                          color: isMe
                                              ? AppTheme.primaryBlue
                                              : AppTheme.white,
                                          borderRadius: BorderRadius.circular(16),
                                        ),
                                        child: Text(
                                          message.content,
                                          style: TextStyle(
                                            color: isMe
                                                ? AppTheme.white
                                                : AppTheme.darkText,
                                            fontSize: 14,
                                          ),
                                        ),
                                      ),
                                      Padding(
                                        padding: const EdgeInsets.only(top: 4),
                                        child: Text(
                                          DateFormat('h:mm a').format(message.timestamp),
                                          style: TextStyle(
                                            fontSize: 10,
                                            color: AppTheme.mediumGray,
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              );
                            },
                          ),
                        ),
                      ),
                      
                      // Message Input
                      Container(
                        padding: const EdgeInsets.all(16),
                        color: AppTheme.white,
                        child: Row(
                          children: [
                            Expanded(
                              child: TextField(
                                controller: _messageController,
                                decoration: InputDecoration(
                                  hintText: 'Type a message...',
                                  filled: true,
                                  fillColor: AppTheme.lightGray,
                                  border: OutlineInputBorder(
                                    borderRadius: BorderRadius.circular(24),
                                    borderSide: BorderSide.none,
                                  ),
                                  contentPadding: const EdgeInsets.symmetric(
                                    horizontal: 20,
                                    vertical: 12,
                                  ),
                                ),
                                onSubmitted: (_) => _sendMessage(),
                              ),
                            ),
                            const SizedBox(width: 8),
                            CircleAvatar(
                              backgroundColor: AppTheme.primaryBlue,
                              child: IconButton(
                                icon: const Icon(Icons.send, color: AppTheme.white),
                                onPressed: _sendMessage,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
          ),
        ],
      ),
    );
  }
  
  void _showGroupInfo() {
    if (_selectedGroup == null) return;
    
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: Text(_selectedGroup!.courseName),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text(
              'Members:',
              style: TextStyle(fontWeight: FontWeight.w600),
            ),
            const SizedBox(height: 8),
            ..._selectedGroup!.members.map((member) {
              return Padding(
                padding: const EdgeInsets.only(bottom: 8),
                child: Row(
                  children: [
                    Container(
                      width: 8,
                      height: 8,
                      decoration: BoxDecoration(
                        color: member.isOnline
                            ? AppTheme.successGreen
                            : AppTheme.mediumGray,
                        shape: BoxShape.circle,
                      ),
                    ),
                    const SizedBox(width: 8),
                    Text(member.name),
                    if (member.id == '1') const Text(' (You)'),
                  ],
                ),
              );
            }),
          ],
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Close'),
          ),
        ],
      ),
    );
  }
}
