// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8BtTeCvP0II7YOZjElCk0Dab3Z0XGqpM',
    appId: '1:1022608019530:web:8d49b3c3a24533b5ed56b3',
    messagingSenderId: '1022608019530',
    projectId: 'upgrade-aa19f',
    authDomain: 'upgrade-aa19f.firebaseapp.com',
    storageBucket: 'upgrade-aa19f.firebasestorage.app',
    measurementId: 'G-YH9G9NEWVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxSqSUl5o96ykdg_44gkjy5KONPZXYL2A',
    appId: '1:1022608019530:android:7a9427a00a423ca4ed56b3',
    messagingSenderId: '1022608019530',
    projectId: 'upgrade-aa19f',
    storageBucket: 'upgrade-aa19f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX2QVfTghI9YY6lR2hTwX2VmNRD-5zqB4',
    appId: '1:1022608019530:ios:f22c6a4cf764b3bbed56b3',
    messagingSenderId: '1022608019530',
    projectId: 'upgrade-aa19f',
    storageBucket: 'upgrade-aa19f.firebasestorage.app',
    iosClientId: '1022608019530-t9a641dft19p87s0mdi1tijrhhi1foof.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX2QVfTghI9YY6lR2hTwX2VmNRD-5zqB4',
    appId: '1:1022608019530:ios:f22c6a4cf764b3bbed56b3',
    messagingSenderId: '1022608019530',
    projectId: 'upgrade-aa19f',
    storageBucket: 'upgrade-aa19f.firebasestorage.app',
    iosClientId: '1022608019530-t9a641dft19p87s0mdi1tijrhhi1foof.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8BtTeCvP0II7YOZjElCk0Dab3Z0XGqpM',
    appId: '1:1022608019530:web:bd77ee521c999bdbed56b3',
    messagingSenderId: '1022608019530',
    projectId: 'upgrade-aa19f',
    authDomain: 'upgrade-aa19f.firebaseapp.com',
    storageBucket: 'upgrade-aa19f.firebasestorage.app',
    measurementId: 'G-XE093HNNWP',
  );
}
