// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCFtAkNty_GsVKJppk8RMDxl0AY0d9Byc',
    appId: '1:476917880453:web:8af10832b7c1111d703bec',
    messagingSenderId: '476917880453',
    projectId: 'upgrade-e87b3',
    authDomain: 'upgrade-e87b3.firebaseapp.com',
    storageBucket: 'upgrade-e87b3.firebasestorage.app',
    measurementId: 'G-GGGMRWQ35V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCynKlyNgC236I8DJ9pqjGpZFKG_Pjx_WE',
    appId: '1:476917880453:android:9924b162dca814c6703bec',
    messagingSenderId: '476917880453',
    projectId: 'upgrade-e87b3',
    storageBucket: 'upgrade-e87b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7msGNOsnmuQZ1VrV7S1ih3dvMrC1k3Gw',
    appId: '1:476917880453:ios:7e2f5865d825d905703bec',
    messagingSenderId: '476917880453',
    projectId: 'upgrade-e87b3',
    storageBucket: 'upgrade-e87b3.firebasestorage.app',
    iosClientId: '476917880453-d7ethsec3bd35am80bial8pucpk0gln9.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3DKfmjVM_CPf6p5tFFVexzSDjHfx3On4',
    appId: '1:476917880453:web:be601da2cab28436703bec',
    messagingSenderId: '476917880453',
    projectId: 'upgrade-e87b3',
    authDomain: 'upgrade-e87b3.firebaseapp.com',
    storageBucket: 'upgrade-e87b3.firebasestorage.app',
    measurementId: 'G-LYX1LPMMWD',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7msGNOsnmuQZ1VrV7S1ih3dvMrC1k3Gw',
    appId: '1:476917880453:ios:7e2f5865d825d905703bec',
    messagingSenderId: '476917880453',
    projectId: 'upgrade-e87b3',
    storageBucket: 'upgrade-e87b3.firebasestorage.app',
    iosClientId: '476917880453-d7ethsec3bd35am80bial8pucpk0gln9.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

}